### TEST GET / WEBSITE 
GET http://localhost:1234 

### Test GET / DASHBOARD
GET http://localhost:1234/dashboard

### Test GET / api/data
GET http://localhost:1234/api/data

### DATA ENDPOINT FOR ADDING A USER
POST http://localhost:1234/api/data
Content-Type: application/json 

{
    "name": "Howdy"
}

### DATA ENDPOINT FOR delete A USER
DELETE  http://localhost:1234/api/data
